### ISSUE TITLE
Set ttl for tcp ports

### ISSUE THREAD

**Issue by packetman007** [kaos/gen_listener_tcp#2]
We want to set sensitive TCP/UDP Ports at low TTL/HOP Leaving other ttl/hop at 128 default

data center = 3
Priv net = 8
Internet = 128 default

Ssh 22 = 8 (internal hop max)
Rdp 3389 = 8
Http 80 = 128 (internet) 
Https 443 = 128
Epmap 135 = 8
MSSQL 1433 = 3 (inside data center)

Netsh can change default, but we want to change defaults by port.

Might we be able to 

1.) Use netsh to set low hop, ttl=8
2.) use listen command to open let's say port 22.
3.) use netsh to change ttl=3
4.) use listen command to open port 1433,

Etc? 

I have no idea if such a thing would work but I'm pretty desperate to set a particular hop TTL for particular TCPUDP ports.

.net 5 can do it for a developed app,

Just not sure how to get it set for a particular general app like SSH or RDP or MSSQL.

I have not found any way to set ports dynamically to the TTL to protect how far it travels.

Appreciate any of your thoughts. I am trying to do this using some form of script batch or setting as opposed to writing and running code. We want to be able to do this without adding any programs.

**Comment by kaos** [comment]
Sorry, I don't see how this has anything to do with the gen_listener_tcp erlang library. Please rephrase if I'm mistaken ;)
Besides that, I'm not currently using nor developing this library any further, so can't really help you further even if your questions relate to this.
